### PR TITLE
cluster: fix the bug for preUpdate #184

### LINKED ISSUE #184: [bug] 3->2 do not do the preUpdate
**Describe the problem**

**To Reproduce**
change replicats in yaml file from 3-->2 , nothing happed to do preUpdate

in updatePod function
```
	// All followers have been updated now, then update leader.
	if leaderPod.Name != "" {
		// When replicas is two (one leader and one follower).
		if len(followerPods) == 1 { <-- should use  s.Spec.replicats == 2
 			if err := s.preUpdate(ctx, leaderPod.Name, followerPods[0].Name); err != nil {
				return err
			}
		}
		// Update the leader.
		if err := s.applyNWait(ctx, &leaderPod); err != nil {
			return err
		}
```

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #184 

### What this PR does?

Summary:
change the `status.replicas` to `Spec.replicas`

### CODE REVIEW

File: cluster/syncer/statefulset.go [hunk 1]
```diff
@@ -251,7 +251,7 @@ func (s *StatefulSetSyncer) updatePod(ctx context.Context) error {
 // 5. Check followerHost current role.
 // 6. If followerHost is not leader, switch it to leader through xenon.
 func (s *StatefulSetSyncer) preUpdate(ctx context.Context, leader, follower string) error {
-	if s.sfs.Status.Replicas != 2 {
+	if s.sfs.Status.Replicas < 2 || *s.sfs.Spec.Replicas != 2 {
```
Comment (andyli029) [inline cluster/syncer/statefulset.go:254]: Add some comments

**Comment by andyli029** [comment]
LGTM.
