### PR TITLE
status: Skip the unavailable node and set default node status. #417

### LINKED ISSUE #417: [bug] Node status and label are incorrect when the node`s xenoncli is not available.
**Describe the problem**

The machine where `sample-mysql-2` is located is closed, but its label and status are not set correctly.

```
root@sm-privatization-test1 ~]# kubectl get pods --show-labels|grep sample
sample-mysql-0                         3/3     Running             3          27h     app.kubernetes.io/component=database,app.kubernetes.io/instance=sample,app.kubernetes.io/managed-by=mysql.radondb.com,app.kubernetes.io/name=mysql,app.kubernetes.io/version=5.7.34,controller-revision-hash=sample-mysql-7d757fd4d4,healthy=no,mysql.radondb.com/cluster=sample,role=FOLLOWER,statefulset.kubernetes.io/pod-name=sample-mysql-0
sample-mysql-1                         3/3     Running             3          27h     app.kubernetes.io/component=database,app.kubernetes.io/instance=sample,app.kubernetes.io/managed-by=mysql.radondb.com,app.kubernetes.io/name=mysql,app.kubernetes.io/version=5.7.34,controller-revision-hash=sample-mysql-7d757fd4d4,healthy=no,mysql.radondb.com/cluster=sample,role=FOLLOWER,statefulset.kubernetes.io/pod-name=sample-mysql-1
sample-mysql-2                         3/3     Running             0          10m     app.kubernetes.io/component=database,app.kubernetes.io/instance=sample,app.kubernetes.io/managed-by=mysql.radondb.com,app.kubernetes.io/name=mysql,app.kubernetes.io/version=5.7.34,controller-revision-hash=sample-mysql-7d757fd4d4,healthy=yes,mysql.radondb.com/cluster=sample,role=LEADER,statefulset.kubernetes.io/pod-name=sample-mysql-2
```

In this case, Node Status should be set to empty or unknown.
```
    Conditions:
      Last Transition Time:  2022-03-16T06:55:47Z
      Status:                False
      Type:                  Lagged
      Last Transition Time:  2022-03-16T06:55:47Z
      Status:                True
      Type:                  Leader
      Last Transition Time:  2022-03-16T06:55:47Z
      Status:                False
      Type:                  ReadOnly
      Last Transition Time:  2022-03-16T06:55:47Z
      Status:                False
      Type:                  Replicating
    Name:                    sample-mysql-2.sample-mysql.default
    Raft Status:
      Leader:  sample-mysql-2.sample-mysql.default:8801
      Nodes:
        sample-mysql-0.sample-mysql.default:8801
        sample-mysql-1.sample-mysql.default:8801
        sample-mysql-2.sample-mysql.default:8801
      Role:     LEADER
```

**To Reproduce**

- Node role should have a default role, use the default role when operator cannot get node`s role.

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

### PR DESCRIPTION
**Pull request by runkecheng**
### What type of PR is this?

/bug

### Which issue(s) this PR fixes?

Fixes #417

### What this PR does?

Summary:

- Do not return err when operator cannot connect to node.
- Provide a default status which is used to unavailable node.

### Special notes for your reviewer?

for test: 
```
helm upgrade demo radondb/mysql-operator --install --set manager.image=runkecheng/mysql-operator --set manager.tag=t0317b
```

### CODE REVIEW

**Comment by runkecheng** [comment]
```
 Last Transition Time:  2022-03-17T02:25:37Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-03-17T03:03:56Z
    Message:               failed to ping host[http://sample-mysql-1.sample-mysql.default:6601/v1/xenon/ping], err: Get "http://sample-mysql-1.sample-mysql.default:6601/v1/xenon/ping": context deadline exceeded
    Status:                True
    Type:                  Error
  Nodes:
    Conditions:
      Last Transition Time:  2022-03-16T06:55:46Z
      Status:                False
      Type:                  Lagged
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                True
      Type:                  Leader
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                False
      Type:                  ReadOnly
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                False
      Type:                  Replicating
    Name:                    sample-mysql-2.sample-mysql.default
    Raft Status:
      Leader:  sample-mysql-2.sample-mysql.default:8801
      Nodes:
        sample-mysql-1.sample-mysql.default:8801
        sample-mysql-0.sample-mysql.default:8801
        sample-mysql-2.sample-mysql.default:8801
      Role:  LEADER
    Conditions:
      Last Transition Time:  2022-03-16T02:16:03Z
      Status:                False
      Type:                  Lagged
      Last Transition Time:  2022-03-16T06:16:39Z
      Status:                False
      Type:                  Leader
      Last Transition Time:  2022-03-16T06:16:39Z
      Status:                True
      Type:                  ReadOnly
      Last Transition Time:  2022-03-17T02:16:47Z
      Status:                True
      Type:                  Replicating
    Name:                    sample-mysql-0.sample-mysql.default
    Raft Status:
      Leader:  sample-mysql-2.sample-mysql.default:8801
      Nodes:
        sample-mysql-1.sample-mysql.default:8801
        sample-mysql-0.sample-mysql.default:8801
        sample-mysql-2.sample-mysql.default:8801
      Role:  FOLLOWER
    Conditions:
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                Unknown
      Type:                  Lagged
      Last Transition Time:  2022-03-17T03:04:06Z
      Status:                False
      Type:                  Leader
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                Unknown
      Type:                  ReadOnly
      Last Transition Time:  2022-03-17T03:04:35Z
      Status:                Unknown
      Type:                  Replicating
    Message:                 dial tcp 10.10.234.166:3306: i/o timeout
    Name:                    sample-mysql-1.sample-mysql.default
    Raft Status:
      Leader:   UNKNOWN
      Role:     UNKNOWN
```

**Comment by acekingke** [comment]
LGTM

File: mysqlcluster/syncer/status.go [hunk 1]
```diff
@@ -296,19 +297,24 @@ func (s *StatusSyncer) updateNodeCondition(node *apiv1alpha1.NodeStatus, idx int
...
+
+	node.RaftStatus = apiv1alpha1.RaftStatus{
+		Role:   string(utils.Unknown),
+		Leader: "UNKNOWN",
+		Nodes:  nil,
+	}
 	raftStatus, err := s.XenonExecutor.RaftStatus(node.Name)
-	if err != nil {
-		return err
+	if raftStatus != nil {
```
Comment (andyli029) [inline mysqlcluster/syncer/status.go]: err need be judged.

**Review by andyli029 — COMMENTED** [review]
LGTM.
