### PR TITLE
api,cluster: fix the bug for status reset leader #178

### LINKED ISSUE #178: [bug] conflict about status controller and preUpdate
**Describe the problem**
In preUpdate funtion `if err = leaderRunner.RunQuery("SET GLOBAL super_read_only=on;"); ` it will change readonly when update, but Status controller will check it preriodic，if found it is readonly , reset it to read write again.
Thus, the operations have confict, so status controller need stop reset it to read write mode  when the cluster is updating

**To Reproduce**

1.

**Expected behavior**
two node updating, stop status controller reset read write mode

**Environment:**

- RadonDB MySQL version:

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #178 

### What this PR does?

Summary:
1. Use the status varibale updating, if preUpdate, set it to be true, if completed, set it to be false

### CODE REVIEW

File: utils/common.go [hunk 1]
```diff
@@ -58,3 +59,34 @@ func GetOrdinal(name string) (int, error) {
 	}
 	return ordinal, nil
 }
+
+//Create the Update file
```
Comment (andyli029) [inline utils/common.go:63]: Add spaces to `//`

File: utils/common.go [hunk 2]
```diff
@@ -58,3 +59,34 @@ func GetOrdinal(name string) (int, error) {
...
+// Create the Update file.
+func TouchUpdateFile() error {
+	var err error
+	var file *os.File
+
+	if file, err = os.Create(FileIndicateUpdate); err != nil {
+		return err
+	}
+	file.Close()
+
```
Comment (andyli029) [inline utils/common.go:72]: Delete the space

File: cluster/syncer/statefulset.go [hunk 3]
```diff
@@ -254,7 +254,8 @@ func (s *StatefulSetSyncer) preUpdate(ctx context.Context, leader, follower stri
 	if s.sfs.Status.Replicas != 2 {
 		return nil
 	}
-
+	utils.TouchUpdateFile()
```
Comment (andyli029) [inline cluster/syncer/statefulset.go:257]: Add space line and add comments

File: cluster/syncer/statefulset.go [hunk 4]
```diff
@@ -255,6 +255,10 @@ func (s *StatefulSetSyncer) preUpdate(ctx context.Context, leader, follower stri
 		return nil
 	}
 
+	// Touch a new preUpdate file ,indicate that preUpdate is going on
+	// remove it when it is finished
```
Comment (andyli029) [inline cluster/syncer/statefulset.go:259]: Add issue #178
