### PR TITLE
*: replace expr commond to bc #725

### LINKED ISSUE #725: create backup job,the backup job is fail
**Describe the problem**

create backup job,but the backup job is fail.the container error info as follows:
 image
**To Reproduce**

1.helm install release with localPVC
2.create cluster 
3.create backup job

**Expected behavior**

**Environment:**

- RadonDB MySQL version:v2.3.0-alpha.1

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #725 

### What this PR does?

Summary:
expr command compare float number uncorrect, use `bc` instead.

### CODE REVIEW

File: backup/syncer/job.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ func (s *jobSyncer) ensurePodSpec(in corev1.PodSpec) corev1.PodSpec {
 			s.backup.Namespace, s.backup.GetNameForJob(), backupToDir, DateTime)
 		// Add the check DiskUsage
 		// use expr because shell cannot compare float number
-		checkUsage := `[ $(expr $(df /backup|awk 'NR>1 {print $4}') \> $(du  /backup |awk 'END {if (NR > 1) {print $1 /(NR-1)} else print 0}')) -eq '1' ] || { echo disk available may be too small; exit 1;};`
+		checkUsage := `[ $(echo "$(df /backup|awk 'NR>1 {print $4}') > $(du  /backup |awk 'END {if (NR > 1) {print $1 /(NR-1)} else print 0}')"|bc) -eq '1' ] || { echo disk available may be too small; exit 1;};`
```
Comment (zhl003) [inline backup/syncer/job.go:163]: I wrote a go language style function that can replace this shell
like this:
```go 
func DirUsage(dir string) (int64, error) {
	var usage int64
	fn := func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}

		st, ok := info.Sys().(*syscall.Stat_t)
		if !ok {
			usage += info.Size()
		} else {
			usage += st.Blocks * 512
		}
		return nil
	}
	if err := filepath.WalkDir(dir, fn); err != nil {
		return 0, err
	}

	return usage, nil
}
```

Comment (acekingke) [reply backup/syncer/job.go:163]: nice，maybe not necessary， shell work good ，and keep sidecar image small
