### PR TITLE
utils: Fix possible misuse of reflect.SliceHeader vet error when go 1.16.6 #139

### LINKED ISSUE #139: make failed when go 1.16.6
**Describe the problem**
make failed when go 1.16.6

**To Reproduce**

```
#make vet
go vet ./...
# github.com/radondb/radondb-mysql-kubernetes/utils
utils/unsafe.go:33:35: possible misuse of reflect.StringHeader
utils/unsafe.go:45:35: possible misuse of reflect.SliceHeader
make: *** [vet] Error 2
```

**Expected behavior**
```
#make vet
go vet ./...

```

**Environment:**

- RadonDB MySQL version:

### PR DESCRIPTION
**Pull request by andyli029**
[summary]
Fix possible misuse of reflect.SliceHeader vet error when go 1.16.6

[test case]
utils/unsafe_test.go

[patch codecov]
utils/unsafe.go 100%

### Which issue(s) this PR fixes?

Fixes #139

### What this PR does?

Summary:

### CODE REVIEW

File: utils/unsafe.go [hunk 1]
```diff
@@ -22,15 +22,18 @@ import (
 )
 
 // BytesToString casts slice to string without copy
-func BytesToString(b []byte) (s string) {
+func BytesToString(b []byte) string {
```
Comment (acekingke) [inline utils/unsafe.go:25]: Why not use string([]byte{xxx})) ?

Comment (andyli029) [reply utils/unsafe.go:25]: without copy

**Comment by zhyass** [comment]
LGTM
