### PR TITLE
controllers: fix the bug cronjob exits when cluster is gone #661

### LINKED ISSUE #661: [bug] cronjob backup still work after remove `backupSchedule`
**Describe the problem**

**To Reproduce**

1. delete the backupSchedule and `kubectl apply -f ` again
2. it will still going on to backup on time

**Expected behavior**

**Environment:**

- RadonDB MySQL version: operator 2.2.1

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #661

### What this PR does?

Summary:
1. when cluster is deleted, remove cronjob
2. when replica is zeror , remove cronjob
3. when backupschedule is set to empty, remove cronjob.

### CODE REVIEW

File: backup/cronbackup.go [hunk 1]
```diff
@@ -36,7 +36,10 @@ func (j *CronJob) Run() {
 	if j.BackupScheduleJobsHistoryLimit != nil {
 		defer j.backupGC()
 	}
-
+	if !j.backupNeedRun() {
+		log.Info("the cron is deleting when cronjob is ")
```
Comment (runkecheng) [inline backup/cronbackup.go:40]: is nil?

**Review by zhl003 — APPROVED** [review]
LGTM

**Review by runkecheng — APPROVED** [review]
