### PR TITLE
controller: fix the 8 backupJob but create 11 copies #237

### LINKED ISSUE #237: Eight S3 backup jobs are created, but 11 backup files are generated
**Describe the problem**

1、create eight S3 backup jobs
image
2、11 backup files are generated
image

**To Reproduce**
1、copy mysql_v1alpha1_backup.yaml file to create 8 backup jobs，the file path：
https://github.com/radondb/radondb-mysql-kubernetes/blob/main/config/samples/mysql_v1alpha1_backup.yaml

2、rename bakup yaml  file metadata.name，each file has a different metadata.name

3、kubectl apply -f mysql_v1alpha1_backup.yaml

**Expected behavior**

8 backup files are generated

**Environment:**

- RadonDB MySQL version:

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #237 

### What this PR does?

Summary:
bug reason:
When backup job created ,but need  updatestatus in next reconcile
before clearHistory, the job has completed, it will delete job, 
So it will recreate again when next reconcile.
fix:
when delete the job, check backup status is completed first.

### CODE REVIEW

File: controllers/backup_controller.go [hunk 1]
```diff
@@ -126,11 +128,24 @@ func (r *BackupReconciler) clearHistoryJob(ctx context.Context, req ctrl.Request
 		if int32(i) >= int32(len(finishedBackups))-historyLimit {
 			break
 		}
-		if err := r.Delete(ctx, job, client.PropagationPolicy(metav1.DeletePropagationBackground)); client.IgnoreNotFound(err) != nil {
-			log.Error(err, "unable to delete old completed job", "job", job)
-		} else {
-			log.V(0).Info("deleted old completed job", "job", job)
+		// at first check backup status completed.
+		backup := backup.New(&apiv1alpha1.Backup{})
+		namespace := types.NamespacedName{
```
Comment (andyli029) [inline controllers/backup_controller.go:133]: Fix the `namespace `

**Comment by andyli029** [comment]
LGTM.
